version: "3"
services:
  rstudio:
    image: rocker/rstudio:latest
    ports:
      - "8787:8787"
    environment:
      - USERNAME=rstudio
      - PASSWORD=rstudio
      - DISABLE_AUTH=true
    volumes:
      - ./work:/home/rstudio/project
